@startuml
left to right direction
skinparam packageStyle rectangle
actor "Мастер" as Master
actor "Клиент" as Client
actor "Администратор" as Admin

package "Система" {

    usecase "Просмотр списка заявок" as UC_Viewing_list_application
    usecase "Найти заявку" as UC_Find_application
    usecase "Просмотр заявки" as UC_Viewing_application
    usecase "Закрыть заявку" as US_closing_application
    usecase "По ФИО" as US_Name

    usecase "Регистрация пользователя" as US_Registr
    usecase "Вход в систему" as US_Enter_sistem
    usecase "создание новой заявки" as US_newzayavka
    usecase "Добавить нового пользователя" as US_New_client
}
Master -- UC_Viewing_list_application
Master -- UC_Find_application
Master -- UC_Viewing_application
Master -- US_closing_application
UC_Find_application --> US_Name:<<include>>

Client -- US_Registr
US_Registr -- US_Enter_sistem
Client -- US_Enter_sistem
Client -- US_newzayavka
Admin -- US_New_client
@end